// Bundles src/ into dist/Code.js for Apps Script.
// - Apps Script has no modules, so esbuild makes one IIFE (global __CT) and this script adds a
//   top-level stub for every export of src/main.js (menus, triggers and the Run button need them).
// - The seed (private/seed.json, else config/seed.example.json) is injected as the global SEED.
import { build } from 'esbuild';
import { existsSync, mkdirSync, readFileSync, writeFileSync, copyFileSync, rmSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';import { validateSeed } from '../src/core/seed.js';

const root = new URL('..', import.meta.url);
const p = (rel) => fileURLToPath(new URL(rel, root));

const seedPath = existsSync(p('private/seed.json')) ? 'private/seed.json' : 'config/seed.example.json';
const seed = JSON.parse(readFileSync(p(seedPath), 'utf8'));
validateSeed(seed);
const out = await build({
  entryPoints: [p('src/main.js')],
  bundle: true,
  format: 'iife',
  globalName: '__CT',
  target: 'es2019',
  write: false,
  legalComments: 'none',
});

const mod = await import(pathToFileURL(p('src/main.js')).href);
const exportsList = Object.keys(mod).filter((k) => typeof mod[k] === 'function');
const stubs = exportsList.map((name) => `function ${name}() { return __CT.${name}.apply(null, arguments); }`).join('\n');

rmSync(p('dist'), { recursive: true, force: true });
mkdirSync(p('dist'), { recursive: true });
writeFileSync(p('dist/Code.js'), [
  '// Generated by scripts/build.mjs. Do not edit; change src/ and rebuild.',
  `var SEED = ${JSON.stringify(seed)};`,  out.outputFiles[0].text,
  stubs,
  '',
].join('\n'));
copyFileSync(p('src/appsscript.json'), p('dist/appsscript.json'));

console.log(`built dist/Code.js (${exportsList.length} entry points: ${exportsList.join(', ')}) with seed from ${seedPath}`);
